# Generated by Django 5.2.4 on 2026-03-05 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Factory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('role', models.CharField(max_length=50)),
                ('salary', models.IntegerField()),
                ('location', models.CharField(max_length=50)),
                ('ph_no', models.IntegerField()),
            ],
        ),
    ]
