# Generated by Django 5.2.4 on 2026-03-05 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Factory', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='factory',
            name='ph_no',
            field=models.BigIntegerField(),
        ),
    ]
