# Generated by Django 5.2.4 on 2026-02-02 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Clients',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('comapany', models.CharField(max_length=50)),
                ('salary', models.IntegerField()),
            ],
        ),
    ]
