# Generated by Django 5.2.4 on 2026-02-02 11:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='clients',
            old_name='comapany',
            new_name='company',
        ),
    ]
