# Generated by Django 5.2.4 on 2026-02-14 05:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('deptno', models.IntegerField(primary_key=True, serialize=False)),
                ('deptname', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Workforce',
            fields=[
                ('wfno', models.IntegerField(primary_key=True, serialize=False)),
                ('wfname', models.CharField(max_length=50)),
                ('salary', models.FloatField()),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workforce_app.department')),
            ],
        ),
    ]
